### ISSUE TITLE
GPU and Memory Requirements for Running ReKep 

### ISSUE THREAD

**Issue by Everloom-129** [huangwl18/ReKep#1]
Hello,

Thank you for your work on ReKep! It is a very solid project. I'm interested in running the model on my RTX 2060 laptop and have a few questions:

## Inference:

- What are the recommended GPU parameters for running ReKep on an RTX 2060?

- How much memory and compute power should I expect for a single scenario?

- Any optimizations for running on a laptop GPU?

- Is there a significant difference in VRAM usage when using external models like VLM or LVM?

## Update:
I found it impossible to run the combination under RTX3090 G
On our lab server, I tried to reproduce the pipeline through Omnigibson. 
- 2 * NVIDIA RTX A6000  , 300W, 49140MiB 
- CUDA Version: 12.3  
But the omnigibson env just keep crash after running 5 min. 

Further, current docker method for running ReKep is not well aligned with the document in gibson. As docker in fact init in a separate space. We would reallly appreciate it if we could have step-by-step guide on correct installation. 

Thanks!

**Comment by 1270645409** [comment]
@Everloom-129  hello! could you share the answer of "How much memory and compute power should I expect for a single scenario?"
Is it possible to reproduce it with 3060 GPU, which has 6 GB VRAM?
Thanks very much! It would help many researchers

**Comment by Quest2GM** [comment]
I tested out ReKep in my recent project, https://github.com/Quest2GM/Koch_VLM_Benchmarks, and was able to run it on a RTX 3060 Laptop GPU with 8GB VRAM. Note that I only tried it for real-world experiments and not simulation.

**Comment by 1270645409** [comment]
> I tested out ReKep in my recent project, https://github.com/Quest2GM/Koch_VLM_Benchmarks, and was able to run it on a RTX 3060 Laptop GPU with 8GB VRAM. Note that I only tried it for real-world experiments and not simulation.

Thank you! I also successfully ran the project on my 3060 GPU, which has 6 GB VRAM. I only tried it for simulation, with ubuntu22.04

**Comment by maojum** [comment]
> > I tested out ReKep in my recent project, https://github.com/Quest2GM/Koch_VLM_Benchmarks, and was able to run it on a RTX 3060 Laptop GPU with 8GB VRAM. Note that I only tried it for real-world experiments and not simulation.
> 
> Thank you! I also successfully ran the project on my 3060 GPU, which has 6 GB VRAM. I only tried it for simulation, with ubuntu22.04

Can you share how it is done? I use the 24g 3060, but it displays out of GPU memory allocating resource'memorymanager allocate'

**Comment by 1270645409** [comment]
> Can you share how it is done? I use the 24g 3060, but it displays out of GPU memory allocating resource'memorymanager allocate'

Sorry, due to the significant differences between our computer environments and project configurations, it's difficult for me to fully understand the memory issue you're encountering. What I can confirm is that running the simulation environment with 6 GB of VRAM should not be a problem. I suspect your issue might be related to OmniGibson (which can be tricky to install). Perhaps you could seek help in the issues section of the OmniGibson repository?

**Comment by maojum** [comment]
> > Can you share how it is done? I use the 24g 3060, but it displays out of GPU memory allocating resource'memorymanager allocate'
> 
> Sorry, due to the significant differences between our computer environments and project configurations, it's difficult for me to fully understand the memory issue you're encountering. What I can confirm is that running the simulation environment with 6 GB of VRAM should not be a problem. I suspect your issue might be related to OmniGibson (which can be tricky to install). Perhaps you could seek help in the issues section of the OmniGibson repository?

Thanks a lot. I will check it
