### ISSUE TITLE
extremely massive amount of proposed keypoints using Realsense RGB-D Camera

### ISSUE THREAD

**Issue by Everloom-129** [huangwl18/ReKep#16]
![image](https://github.com/user-attachments/assets/c6b4d2ea-11c6-40df-8158-a539790e0ab8)
Hi everyone,

I’m reproducing the ReKep experiment with a Realsense RGB-D camera(d435) , but I'm encountering some issues. The pipeline consistently generates many proposed keypoints, and the results are not as expected. I suspect the following factors could be contributing to the problem:

-  Workspace constraints in the configuration may not match the robot's actual setup.

- The scene complexity is higher than in the original setup (which used a wrist-mounted FPV camera).

Additionally, I'm facing instances where the k-means algorithm fails to converge. I guess it may related to the issue above. Any suggestions on troubleshooting or improving these aspects would be appreciated.
![image](https://github.com/user-attachments/assets/ab9e9675-3d45-4a3b-8907-0aa24ef559c0)

---

Update: After configuring the Kmeans & replace the meanshift with DBSCAN, my pipeline performs much better now:

![image-20241024204918662](https://github.com/user-attachments/assets/952f9899-dbd5-4772-87c9-0925c6b0f9d4)

![image-20241024213217406](https://github.com/user-attachments/assets/2719d492-48f9-4b56-a0ab-c76a572d1f38)

![image-20241024213103184](https://github.com/user-attachments/assets/4d947d1b-eda9-4f4a-ae26-f895e9c6369a)

thanks everyone for sharing insights, I am open to contact if you are also doing reproduction in the real world. Just drop me a msg by [tonyw3@seas.upenn.edu](mailto:tonyw3@seas.upenn.edu) with a short Bio plus your wechat / discord

**Comment by Everloom-129** [comment]
Update:
```bash
(sam2) tonyw@pal:~/VLM/ReKep$ sh vision.sh 
# main
Debug: Input image shape: (480, 640, 3)
Debug: Input depth shape: (480, 640)
Debug: Generated 22 masks
Debug: masks shape: (480, 640)
Debug: Type of masks: <class 'list'>
Debug: Generated point cloud with shape: (307200, 3)
# proposal part
Debug: shape_info: {'img_h': 480, 'img_w': 640, 'patch_h': 34, 'patch_w': 45}
Debug: transformed_rgb shape: (476, 630, 3)
Debug: interpolated_feature_grid shape: torch.Size([480, 640, 384])
Debug: features_flat shape: torch.Size([307200, 384])
Debug: points shape: (307200, 3)
Debug: features_flat shape: torch.Size([307200, 384])
Debug: number of mask groups: 22
Debug: shape of first mask group: (480, 640)
Debug: shape of first mask: (480, 640)
Debug: feature_points shape: (10124, 3)
Debug: feature_pixels shape: (10124, 2)
Debug: obj_features_flat shape: torch.Size([10124, 384])
```

above is the input data shape I input system

Here is my fork version for rgbd camera depolyment: 

https://github.com/Everloom-129/ReKep/blob/vision_w_rgbd/keypoint_proposal.py

**Comment by Sui0206** [comment]
Can you check that is there any NaN value in your K array before your K-means?

**Comment by Everloom-129** [comment]
> Can you check that is there any NaN value in your K array before your K-means?

Hi, I have checked my cluster data array, there is no NaN in it
![image](https://github.com/user-attachments/assets/898e6844-2277-4056-8650-57c2c5845ac3)

further is a very simple scene, and there are still a large amount of keypoints

**Comment by yanrihong** [comment]
I'm trying to deploy ReKep to a real machine recently. Can I add you on WeChat to discuss?

**Comment by ClaireZixiWang** [comment]
Hey folks, I'm trying to replicate ReKep and deploy on real robots as well. Would love to discuss! I'm down for email/discord/wechat/etc

**Comment by Everloom-129** [comment]
@yanrihong @ClaireZixiWang Hi, you could send me an email: tonyw3@seas.upenn.edu with a short Bio plus your wechat id. Welcome to discuss more on real world deployment!

**Comment by Bailey-24** [comment]
I think it's better to let the photo focus on the workspace.
![image](https://github.com/user-attachments/assets/888e88b4-3a35-417b-8324-93ec2989ab36)

**Comment by pmj110119** [comment]
The reason may be that the segmentation mask you provided is too fragmented.

**Comment by Everloom-129** [comment]
> I think it's better to let the photo focus on the workspace. ![image](https://private-user-images.githubusercontent.com/72083251/379705039-888e88b4-3a35-417b-8324-93ec2989ab36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NzYwNjUsIm5iZiI6MTcyOTg3NTc2NSwicGF0aCI6Ii83MjA4MzI1MS8zNzk3MDUwMzktODg4ZTg4YjQtM2EzNS00MTdiLTgzMjQtOTNlYzI5ODlhYjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE3MDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZDgyMTU3ZTVhNDkxMzIzM2YyM2U0NjgwZDZiNGVjMmFjNWRjZGEyMDVlMzE1NjNjNWYyMzNlZTZjYWRmYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U0_Y-LwRaa_19RQ48Ku-HYOqFXAri9LUfwn4u5bvOLg)

Hi Bailey, I didn't set workspace bound and use a soft area instead to test more cases. 

Thx for the advice, i will add this in following experiments

**Comment by Everloom-129** [comment]
> The reason may be that the segmentation mask you provided is too fragmented.

I use SAM2-L  [sam2.1_hiera_large.pt](https://dl.fbaipublicfiles.com/segment_anything_2/092824/sam2.1_hiera_large.pt)

Have you tried smaller SAM or setting its config?

Possibly will get better with this

**Comment by pmj110119** [comment]
By observing the keypoint visualizations provided by paper and the ground truth masks generated by simulator, it's clear that the masks are instance-level and relatively clean (masks of background were easily filtered by `self.config['max_mask_ratio']`). 

However, in a real-world environment, your complex background may cause SAM to generate numerous fragmented masks. (This fragmentation also contributed to the convergence issues you previously encountered with k-means.) 

The author filters out excessively large masks (mainly large background areas) in the code. However, given your complex background, I recommend additionally filtering out small masks too:

```
    ''' 
    ReKep/keypoint_proposal.py:110 
    '''

    def _cluster_features(self, points, features_flat, masks):
        candidate_keypoints = []
        candidate_pixels = []
        candidate_rigid_group_ids = []
        for rigid_group_id, binary_mask in enumerate(masks):
            # ignore mask that is too large
            if np.mean(binary_mask) > self.config['max_mask_ratio']:
                continue


           # extra code you should add
            if np.mean(binary_mask) < self.config['min_mask_ratio']:
                continue
```

**Comment by Sam-Firefly** [comment]
Hello! What a fantastic work you made! It helps me a lot! 
But I also meet the problem that the *center_shift=nan*. May I know what you've done about k-means algorithum? The last link seems disable? 

![image](https://github.com/user-attachments/assets/1b4426fe-bfb9-4136-9314-5866139d69fe)
![image](https://github.com/user-attachments/assets/5b70e4dd-4673-4843-8a36-e48903249a16)

**Comment by Everloom-129** [comment]
Hi @Sam-Firefly , please refer my newest branch, the old one has been merged
https://github.com/Everloom-129/ReKep/blob/vision_r2d2/rekep/keypoint_proposal.py
