### ISSUE TITLE
Issue when running the demo

### ISSUE THREAD

**Issue by ge79puv** [huangwl18/ReKep#20]
Hey there,

I am trying to run the demo of "python main.py --use_cached_query --visualize" with Isaac Sim 4.1.0 and OmniGibson v1.1.1. However, when I use one RTX 6000 (24G) to run the script, one error occurs immediately as follows:

![image](https://github.com/user-attachments/assets/556ae9d0-94f8-4201-ac8c-cc862d4a8185)

Do you know what is the reason for this? And how can I fix it?

Thanks a lot in advance!

**Comment by taeyeopl** [comment]
@ge79puv I have the same issue. Could you share how to solve the problem?

**Comment by ge79puv** [comment]
@taeyeopl , Hi, here is the solution: https://github.com/huangwl18/ReKep/issues/12

**Comment by curry2736** [comment]
@ge79puv Were you able to get this to work with headless mode?

Receiving `AssertionError: Simulation step dt (0.06666666666666667) must be equal to rendering dt (0.03333333333333333) when gm.HEADLESS is set!` when running the command `OMNIGIBSON_HEADLESS=1 python main.py --use_cached_query`

**Comment by ge79puv** [comment]
@curry2736 @huangwl18 Hi, I also have this issue when I tried the headless mode. I also want to fix that.

**Comment by curry2736** [comment]
@ge79puv I fixed it by commenting out the code block here - 
https://github.com/StanfordVL/OmniGibson/blob/255a4e4fb42fa4d2f1a43a94de37085474db4377/omnigibson/simulator.py#L521-L527
